### PR TITLE
Iam role

### PR DESCRIPTION
**Pull request by franc-carter**
Hi,

I've added support for using the credentials from the EC2 Instance metadata so that IAM Roles can be used.
- added an iam_role= mount option
- credentials are refreshed 20 minutes before expiry

cheers

### CODE REVIEW

**Comment by Downchuck** [comment]
This patch seems to force the use of iam-role; I may be misreading things, but I'm seeing : "s3fs: could not get new credentials" in my logs when I try to mount, and my reading of the patch shows get_iam_credentials being run without checking whether or not the flag is set.

**Comment by franc-carter** [comment]
Can you give me some more detail on how you are producing this error and I'll try to debug.

I've tried not specifying the iam_role and I get different behaviour. The code should only try iam when the option is passed, but maybe I've missed something

**Comment by Downchuck** [comment]
I'm having a general issue with authentication anyway on an earlier commit; seems like it's not picking up my authentication credentials (or I don't have them in the right format). So this may be a non-issue. [Line 357](https://github.com/tongwang/s3fs-c/blob/3ebbf693ecfc42e9ed0cd1ecdc9cbdf8147e1103/src/s3fs.cpp#L357) was showing up in my logs, so I thought it was an issue where iam was being called regardless of settings.

**Comment by franc-carter** [comment]
You are right - the code I use for timeout on the credentials is not correct ;-( I'm putting a fix together now

sorry

**Comment by franc-carter** [comment]
Hopefully fixed on my iam-role branch at

https://github.com/franc-carter/s3fs-c/tree/iam-role

Once I've tested that the credentials refresh when using iam_role I will do an upstream pull-request

**Comment by franc-carter** [comment]
credentials refresh checked out so i have merged the commits back into my master and requested a pull

**Pull request merged**
